feat(seo): Подключил модуль SEO V1
15web/symfony-starter-kit pull request #102
Opened 2023-05-08 11:20 UTC by rleekg

META: #91623

2023-05-18 12:07 UTC, pchelk1n requested changes

2023-05-18 12:07 UTC, pchelk1n commented on backend/src/Infrastructure/SeoResourceType.php
> +namespace App\Infrastructure;
Почему в инфре? В модуль же?

2023-05-18 12:07 UTC, pchelk1n commented on backend/src/Seo/Command/SaveSeoCommand.php
> +        public ?string $title,
Обязательное поле. Идея какая, если данных нет, то и не надо вызывать ручку сохранения сео данных.

2023-05-18 12:07 UTC, pchelk1n commented on backend/src/Seo/Domain/Seo.php
> +        string $identity,
Добавь title, смысл тогда добавлять сео данные, если совсем ничего не передали.

2023-07-01 14:52 UTC, rleekg commented on backend/tests/Functional/Seo/SeoTest.php
> +        $token = User::auth();
вынес в Seo::create

2023-07-01 14:52 UTC, rleekg commented on backend/tests/Functional/Seo/Admin/SeoSaveTest.php
> +#[TestDox('Сохранение настройки')]
да чет не то выкатилось исправил

2023-07-01 14:58 UTC, rleekg commented on backend/src/Infrastructure/SeoResourceType.php
> +namespace App\Infrastructure;
это у нас типа контракта же?
Сео же точно не может знать какие типы сео будет сохранять? 

Смотрел в сторону динамического енума, или типа того чтобы значения можно было собрать агрегатором

2023-07-01 14:58 UTC, rleekg commented on backend/src/Seo/Command/SaveSeoCommand.php
> +        public ?string $title,
исправил

2023-07-01 15:03 UTC, rleekg commented on backend/src/Seo/Domain/Seo.php
> +        string $identity,
добавил

2023-07-06 12:58 UTC, pchelk1n commented on backend/src/Infrastructure/SeoResourceType.php
> +namespace App\Infrastructure;
Это его экспертные знания, которые не надо шарить в инфраструктуру.

2023-07-09 07:46 UTC, rleekg commented on backend/src/Infrastructure/SeoResourceType.php
> +namespace App\Infrastructure;
вынес из инфраструктцры

2023-07-12 13:58 UTC, pchelk1n approved these changes

2023-07-12 13:58 UTC, merged