feat(apiRequest): Вынес атрибут ApiRequest.php в экшн контроллера и команды
15web/symfony-starter-kit pull request #103
Opened 2023-05-16 19:08 UTC by kendaskedo

- Вынес атрибут ApiRequest.php в экшны контроллеров
- Подправил сам класс ApiRequest (сменил на Attribute::TARGET_PARAMETER)

META: #92933

2023-05-19 06:13 UTC, pchelk1n requested changes

2023-05-19 06:13 UTC, pchelk1n commented on backend/src/Infrastructure/ApiRequestResolver/ApiRequestArgumentValueResolver.php
> +            return [];
ApiBadRequestException

2023-05-19 17:20 UTC, kendaskedo commented on backend/src/Infrastructure/ApiRequestResolver/ApiRequestArgumentValueResolver.php
> +            return [];
Подправил

2023-05-20 10:16 UTC, pchelk1n approved these changes

2023-05-20 10:17 UTC, merged