fix(infra): Починил типизацию ApiRequest
15web/symfony-starter-kit pull request #106
Opened 2023-06-23 10:45 UTC by antode

META: #92933

2023-06-23 12:05 UTC, pchelk1n requested changes

2023-06-23 12:05 UTC, pchelk1n commented on backend/src/Infrastructure/ApiRequestResolver/ApiRequestArgumentValueResolver.php
> + * @template GenericApiRequest of object
Может назвать TemplateApiRequest или ТObject, TApiRequets?

2023-06-26 05:36 UTC, antode commented on backend/src/Infrastructure/ApiRequestResolver/ApiRequestArgumentValueResolver.php
> + * @template GenericApiRequest of object
Давай `TApiRequest`, в единственном числе?

2023-06-26 07:16 UTC, pchelk1n commented on backend/src/Infrastructure/ApiRequestResolver/ApiRequestArgumentValueResolver.php
> + * @template GenericApiRequest of object
Давай

2023-06-28 09:53 UTC, antode commented on backend/src/Infrastructure/ApiRequestResolver/ApiRequestArgumentValueResolver.php
> + * @template GenericApiRequest of object
Сделал

2023-07-01 06:43 UTC, pchelk1n approved these changes

2023-07-01 06:43 UTC, merged