refactor(composer): зависимости psalm перемещены в require-dev
15web/symfony-starter-kit pull request #125
Opened 2023-09-18 21:20 UTC by GhostlyIT

Meta: #94958

2023-09-19 06:46 UTC, pchelk1n commented
```
docker compose run --rm backend composer depends phpdocumentor/reflection-docblock
[+] Creating 1/0
✔ Container symfony-starter-kit-local-mysql-1 Running 0.0s
15web/symfony-starter-kit - requires phpdocumentor/reflection-docblock (^5.3)
felixfbecker/advanced-json-rpc v3.2.1 requires phpdocumentor/reflection-docblock (^4.3.4 || ^5.0.0)
symfony/framework-bundle v6.3.1 conflicts phpdocumentor/reflection-docblock (<3.2.2)
symfony/mime v6.3.0 conflicts phpdocumentor/reflection-docblock (<3.2.2)
symfony/property-info v6.3.0 conflicts phpdocumentor/reflection-docblock (<5.2)
symfony/serializer v6.3.1 conflicts phpdocumentor/reflection-docblock (<3.2.2)
symfony/twig-bridge v6.3.0 conflicts phpdocumentor/reflection-docblock (<3.2.2)
```

Данный пакет phpdocumentor/reflection-docblock нужен felixfbecker/advanced-json-rpc, который нужен псалму https://github.com/vimeo/psalm/blob/5.x/composer.json

Вот тут можно глянуть https://github.com/felixfbecker/php-advanced-json-rpc/blob/master/composer.json

Поэтому нам эта зависимость в композере вообще не нужна, ее должен был поставить псалм.
Попробуй удалить псалм и поставить снова.

Далее про пхпстан
В свою очередь phpdocumentor/reflection-docblock нужен phpdocumentor/type-resolver которому как раз нужен phpstan/phpdoc-parser

Т.е. эти зависимости можно вообще из нашего композера убрать.

2023-09-19 06:49 UTC, pchelk1n requested changes
```
docker compose run --rm backend composer depends phpdocumentor/reflection-docblock
[+] Creating 1/0
✔ Container symfony-starter-kit-local-mysql-1 Running 0.0s
15web/symfony-starter-kit - requires phpdocumentor/reflection-docblock (^5.3)
felixfbecker/advanced-json-rpc v3.2.1 requires phpdocumentor/reflection-docblock (^4.3.4 || ^5.0.0)
symfony/framework-bundle v6.3.1 conflicts phpdocumentor/reflection-docblock (<3.2.2)
symfony/mime v6.3.0 conflicts phpdocumentor/reflection-docblock (<3.2.2)
symfony/property-info v6.3.0 conflicts phpdocumentor/reflection-docblock (<5.2)
symfony/serializer v6.3.1 conflicts phpdocumentor/reflection-docblock (<3.2.2)
symfony/twig-bridge v6.3.0 conflicts phpdocumentor/reflection-docblock (<3.2.2)
```

Данный пакет phpdocumentor/reflection-docblock нужен felixfbecker/advanced-json-rpc, который нужен псалму https://github.com/vimeo/psalm/blob/5.x/composer.json

Вот тут можно глянуть https://github.com/felixfbecker/php-advanced-json-rpc/blob/master/composer.json

Поэтому нам эта зависимость в композере вообще не нужна, ее должен был поставить псалм.
Попробуй удалить псалм и поставить снова.

Далее про пхпстан
В свою очередь phpdocumentor/reflection-docblock нужен phpdocumentor/type-resolver которому как раз нужен phpstan/phpdoc-parser

Т.е. эти зависимости можно вообще из нашего композера убрать.

2023-09-19 07:49 UTC, GhostlyIT commented
@pchelk1n Действительно, переустановка псалма помогла избавиться от лишних пакетов

2023-09-20 06:22 UTC, pchelk1n approved these changes
Ага гуд.

2023-09-20 06:22 UTC, merged