refactor(composer): обновлены все пакеты, пофикшены ошибки и деприкейшены
15web/symfony-starter-kit pull request #126
Opened 2023-09-18 22:46 UTC by GhostlyIT

Meta: #94958

2023-09-19 06:56 UTC, pchelk1n requested changes

2023-09-19 06:56 UTC, pchelk1n commented on backend/config/packages/doctrine.yaml
> +        report_fields_where_declared: true
А это для чего?

2023-09-19 06:56 UTC, pchelk1n commented on backend/src/Article/Domain/Articles.php
> +    public function __construct(private EntityManagerInterface $entityManager) {}
Это фиксер скукожил конструктор? Если да, надо найти что за правило появилось у негов доке.

2023-09-19 19:15 UTC, GhostlyIT commented on backend/config/packages/doctrine.yaml
> +        report_fields_where_declared: true
Новая фича в doctrine/orm 2.16, которая улучшает вывод ошибок при некорректном маппинге полей. Тут можно почитать подробнее: https://github.com/doctrine/orm/pull/10455 

Без этого конфига сейчас выбрасывается исключение

2023-09-19 20:45 UTC, GhostlyIT commented on backend/src/Article/Domain/Articles.php
> +    public function __construct(private EntityManagerInterface $entityManager) {}
Да, это в новых версиях фиксера добавили параметр **single_line_empty_body**. Я установил его в false и все стало намного красивей

2023-09-20 13:58 UTC, GhostlyIT commented on backend/src/Article/Domain/Articles.php
> +    public function __construct(private EntityManagerInterface $entityManager) {}
Вот ссылка: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/basic/single_line_empty_body.rst

Правило относится к PER, а не к PSR. Мы ему следуем?

Вот тут https://www.php-fig.org/per/coding-style/#4-classes-properties-and-methods говорится, что у пустых классов фигурные скобки следует располагать на одной строке с ним

2023-09-23 05:39 UTC, pchelk1n commented on backend/src/Article/Domain/Articles.php
> +    public function __construct(private EntityManagerInterface $entityManager) {}
Хм, ладно подумаем.

2023-09-23 05:42 UTC, pchelk1n approved these changes

2023-09-23 05:42 UTC, merged