refactor(config): конфиги перемещены в src-dev
15web/symfony-starter-kit pull request #138
Opened 2023-10-03 14:05 UTC by GhostlyIT

Meta: #95126

2023-10-07 07:58 UTC, pchelk1n commented
А давай еще .spectral.yaml и openapi.yaml тоже перенесем?

2023-10-07 07:58 UTC, pchelk1n requested changes

2023-10-07 07:58 UTC, pchelk1n commented on backend/src-dev/rector.php
> +    $rectorConfig->cacheDirectory('/app/var/cache/rector');
А не получается __DIR__'../' вместо app?

2023-10-07 10:48 UTC, GhostlyIT commented
> А давай еще .spectral.yaml и openapi.yaml тоже перенесем?

А openapi нам не нужен на проде разве?

2023-10-09 11:24 UTC, GhostlyIT commented on backend/src-dev/rector.php
> +    $rectorConfig->cacheDirectory('/app/var/cache/rector');
Не работает почему-то именно со скипом правил, поэтому я решил сделать однообразно во всем файле.

2023-10-11 09:41 UTC, pchelk1n commented
> > А давай еще .spectral.yaml и openapi.yaml тоже перенесем?
> 
> А openapi нам не нужен на проде разве?

А зачем он на проде?

2023-10-11 14:01 UTC, pchelk1n commented on backend/src-dev/rector.php
> +    $rectorConfig->cacheDirectory('/app/var/cache/rector');
Доработал, сделал через dirname

2023-10-11 14:10 UTC, merged