refactor(openapi): убрал все refs, которые использовались 1 раз
15web/symfony-starter-kit pull request #146
Opened 2023-10-24 07:39 UTC by ZhuZhu15

Meta #95469

2023-10-24 14:21 UTC, pchelk1n requested changes

2023-10-24 14:21 UTC, pchelk1n commented on backend/src-dev/openapi.yaml
> +                            required:
password же тоже required?

2023-10-24 14:31 UTC, ZhuZhu15 commented on backend/src-dev/openapi.yaml
> +                            required:
Брал cхему из того что было в refs, required не смотрел
https://github.com/15web/symfony-starter-kit/pull/146/files#diff-c09addf041b8a9c38651ed70216f9aa58ae300111f5f3fe0b52aaab5f400e12eL1029

а так вообще да, password должен быть

2023-10-25 09:56 UTC, pchelk1n approved these changes
Гуд

2023-10-25 09:57 UTC, merged