remove(security-bundle): удалил security-bundle
15web/symfony-starter-kit pull request #156
Opened 2024-03-06 11:59 UTC by vasilevdm

META: #97872

2024-03-11 13:09 UTC, pchelk1n requested changes

2024-03-11 15:19 UTC, vasilevdm commented on backend/src/User/SignIn/Command/SignInCommand.php
> +        Assert::stringNotEmpty($password);
Заменил на `non-empty-string`

Изначально сделал чтобы явно проверить на пустую строку. Но судя по коду это не имеет большого смысла т.к. 
 еще на этапе маппинга реквеста на объект `SignInRequest` тип  `non-empty-string` будет проверен валинором

2024-03-12 13:59 UTC, psprokofiev approved these changes

2024-03-13 07:26 UTC, antode approved these changes

2024-03-13 11:04 UTC, merged