feat (user): Подключил сервис для хеширования пароля
15web/symfony-starter-kit pull request #167
Opened 2024-03-20 19:10 UTC by GhostlyIT

Meta: #98078

2024-03-21 13:18 UTC, pchelk1n requested changes

2024-03-21 13:18 UTC, pchelk1n commented on backend/src-dev/User/Service/TestPasswordHasher.php
> +final readonly class TestPasswordHasher implements PasswordHasherInterface
#[When('test')] не надо?

2024-03-22 16:22 UTC, GhostlyIT commented on backend/src-dev/User/Service/TestPasswordHasher.php
> +final readonly class TestPasswordHasher implements PasswordHasherInterface
Наверное надо, но и без этого работало) Добавил

2024-03-25 07:42 UTC, psprokofiev commented on backend/src/Infrastructure/HasherInterface.php
> +    public function verify(string $data, string $hash): bool;
а почему здесь решил не указывать строгие типы?

2024-03-25 07:42 UTC, psprokofiev commented on backend/src/User/Service/PasswordHasher.php
> +    private const int HASH_COST = 13;
не слишком ли дорого по ресурсам выйдет 13 проходов?  
в ларке было раньше 10, увеличили до 12 https://github.com/laravel/laravel/pull/6245
у меня был опыт когда я увеличивал выше, и приложение просто ложилось...

2024-03-25 07:42 UTC, psprokofiev commented on backend/src/User/Service/PasswordHasher.php
> +    private const int HASH_COST = 13;
а еще я бы это вынес в конфиг (в енв), чтобы можно было менять число проходов без изменения кода

2024-03-25 08:16 UTC, GhostlyIT commented on backend/src/User/Service/PasswordHasher.php
> +    private const int HASH_COST = 13;
А я в чьем-то комменте увидел про 13 в санктуме текущем, поэтому так и сделал

2024-03-25 08:46 UTC, GhostlyIT commented on backend/src/User/Service/PasswordHasher.php
> +    private const int HASH_COST = 13;
Вынес в env и по дефолту поставил 10. Если нужно будет - увеличим уже в проекте

2024-03-25 08:46 UTC, GhostlyIT commented on backend/src/Infrastructure/HasherInterface.php
> +    public function verify(string $data, string $hash): bool;
Пропустил. Поправил

2024-03-25 14:47 UTC, pchelk1n requested changes
Еще надо заребейзить и конфликты порешать.

2024-03-25 14:47 UTC, pchelk1n commented on backend/src/Infrastructure/HasherInterface.php
> +interface HasherInterface
А если убрать слово Interface и будет просто Hasher

2024-03-25 14:47 UTC, pchelk1n commented on backend/src/User/SignIn/Command/SignIn.php
> +        private HasherInterface $passwordHasher
$hasher

2024-03-25 14:47 UTC, pchelk1n commented on docker/backend/.env.dist
> +PASSWORD_HASH_COST=12
10?

2024-03-25 14:47 UTC, pchelk1n commented on backend/src/User/Service/PasswordHasher.php
> +    private const int HASH_COST = 13;
А в ПР стоит 12

2024-03-25 16:49 UTC, GhostlyIT commented on backend/src/Infrastructure/HasherInterface.php
> +interface HasherInterface
Привык везде с суффиксом писать, да и PSR говорит, что нужно суффикс проставлять интерфейсам - https://www.php-fig.org/bylaws/psr-naming-conventions/ (первая же строчка)

2024-03-25 16:55 UTC, GhostlyIT commented on docker/backend/.env.dist
> +PASSWORD_HASH_COST=12
Да, оказалось не там сделал дефолт

2024-03-25 16:55 UTC, GhostlyIT commented on backend/src/User/Service/PasswordHasher.php
> +    private const int HASH_COST = 13;
поправил

2024-03-26 06:32 UTC, pchelk1n commented on backend/src/Infrastructure/HasherInterface.php
> +interface HasherInterface
Вот можно почитать https://leonidchernenko.ru/psr-interface-suffixes/ там еще ссылка на обсуждение в гитхабе.

2024-03-26 06:33 UTC, pchelk1n commented on backend/src/Infrastructure/HasherInterface.php
> +     * @param non-empty-string $data
return non-empty-string?

2024-03-26 13:32 UTC, GhostlyIT commented on backend/src/Infrastructure/HasherInterface.php
> +interface HasherInterface
Любимые холивары) Ок, давайте тогда без суффикса везде использовать

2024-03-28 12:06 UTC, pchelk1n approved these changes

2024-03-28 12:06 UTC, merged