99261-build-update-dependencies
15web/symfony-starter-kit pull request #171
Opened 2024-06-12 07:45 UTC by GhostlyIT

Meta: #99261

2024-07-11 06:38 UTC, psprokofiev requested changes

2024-07-11 06:38 UTC, psprokofiev commented on backend/.gitignore
> +###< qossmic/deptrac ###
это убрать наверно надо, кэш же в другом месте лежит

2024-07-11 09:04 UTC, GhostlyIT commented on backend/.gitignore
> +###< qossmic/deptrac ###
Ну да, это рецепт туда вписал

2024-07-18 11:15 UTC, psprokofiev approved these changes

2024-07-29 07:25 UTC, pchelk1n approved these changes

2024-07-29 07:25 UTC, merged