feat(user/change-password): добавил ручку смены текущего пароля
15web/symfony-starter-kit pull request #174
Opened 2024-07-16 07:49 UTC by psprokofiev

META: #99623

2024-07-16 19:18 UTC, GhostlyIT requested changes
Что то мне еще не нравится название модуля ChangePassword. Может, лучше просто Password назовем? Мне кажется, модули лучше называть существительными.

2024-07-16 19:18 UTC, GhostlyIT commented on backend/src/User/ChangePassword/Http/ChangePasswordAction.php
> +        $this->logger->info('Пользователь запросил смену пароля пароль', [
Слово "пароль" лишнее

2024-07-16 19:18 UTC, GhostlyIT commented on backend/src-dev/Tests/Functional/User/ChangePassword/ChangePasswordTest.php
> +    public static function notValidEmailDataProvider(): Iterator
Название метода нужно поменять

2024-07-18 08:07 UTC, psprokofiev commented on backend/src-dev/Tests/Functional/User/ChangePassword/ChangePasswordTest.php
> +    public static function notValidEmailDataProvider(): Iterator
исправил

2024-07-18 08:07 UTC, psprokofiev commented on backend/src/User/ChangePassword/Http/ChangePasswordAction.php
> +        $this->logger->info('Пользователь запросил смену пароля пароль', [
убрал

2024-07-18 08:09 UTC, psprokofiev commented
> Что то мне еще не нравится название модуля ChangePassword. Может, лучше просто Password назовем? Мне кажется, модули лучше называть существительными.

ну кстати да, переименовал модуль просто в Password, и Recovery в него же перенес  
так выглядит приятнее

2024-07-21 11:05 UTC, GhostlyIT approved these changes

2024-08-01 09:14 UTC, pchelk1n requested changes

2024-08-01 09:14 UTC, pchelk1n commented on backend/src-dev/openapi.yaml
> +                description: Текущий пароль
minLength?

2024-08-01 09:14 UTC, pchelk1n commented on backend/src/User/Password/Http/ChangePasswordRequest.php
> +        Assert::minLength($this->newPassword, 6);
А $currentPassword проверить?

2024-08-01 09:14 UTC, pchelk1n commented on backend/src/User/Password/Http/ChangePasswordRequest.php
> +            throw new ApiBadRequestException(['Пароль и его подтверждение не совпадают']);
Такие исключения может только экшн бросать, тут Imvalid от моцарта можно бросить.

2024-08-01 09:16 UTC, pchelk1n requested changes

2024-08-01 09:16 UTC, pchelk1n commented on backend/src/User/Password/Http/ChangePasswordAction.php
> +
Не увидел удаление токенов.

2024-08-01 13:50 UTC, psprokofiev commented on backend/src/User/Password/Http/ChangePasswordRequest.php
> +        Assert::minLength($this->newPassword, 6);
а зачем нам его валидировать здесь?
а если вчера была было требование 6 символов, а сегодня мы обновили до 8 символов
это значит чел не сможет ввести текущий пароль

2024-08-01 13:51 UTC, psprokofiev commented on backend/src-dev/openapi.yaml
> +                description: Текущий пароль
не, тут не надо вообще ничего валидировать

2024-08-01 14:01 UTC, psprokofiev commented on backend/src/User/Password/Http/ChangePasswordAction.php
> +
\App\User\Password\Command\ChangePassword
здесь лежало, но переместил в ручку

2024-08-01 14:01 UTC, psprokofiev commented on backend/src/User/Password/Http/ChangePasswordRequest.php
> +            throw new ApiBadRequestException(['Пароль и его подтверждение не совпадают']);
ну кстати да, переделал на ассерты

2024-08-02 08:14 UTC, pchelk1n approved these changes

2024-08-02 08:14 UTC, merged