feat(signUp): Доработал регистрацию, добавил ввод пароля и подтверждение email
15web/symfony-starter-kit pull request #43
Opened 2022-11-03 13:17 UTC by rleekg

META: #88815

2022-11-04 11:23 UTC, pchelk1n requested changes

2022-11-04 11:23 UTC, pchelk1n commented on backend/tests/Functional/User/ConfirmEmailTest.php
> +        self::assertApiError($response, ApiErrorCode::EmailAlreadyIsConfirmed->value);
Добавь тест на 404 токен не найден

2022-11-04 11:23 UTC, pchelk1n commented on backend/src/User/SignUp/Http/ConfirmEmailAction.php
> +#[ParamConverter('user', class: User::class, options: ['mapping' => ['confirmToken' => 'userEmail.confirmToken']])]
Может лучше метод в Users findByConfirmToken? В нем будут инкапсулированы все детали, а так детали протекли в хттп.   Подумай может юзера будет доставать хендлер команды
confirmEmail, а не извне приходить.. Как раз там тебе и поможет дто команда, в которой будет confirmCode

2022-12-01 17:25 UTC, rleekg commented on backend/tests/Functional/User/ConfirmEmailTest.php
> +        self::assertApiError($response, ApiErrorCode::EmailAlreadyIsConfirmed->value);
добавил

2022-12-01 17:26 UTC, rleekg commented on backend/src/User/SignUp/Http/ConfirmEmailAction.php
> +#[ParamConverter('user', class: User::class, options: ['mapping' => ['confirmToken' => 'userEmail.confirmToken']])]
сделал метод findByConfirmToken в Users, команда принимает Uuid  и ищет пользователя, подтверждает

2022-12-02 14:21 UTC, pchelk1n approved these changes

2022-12-02 14:21 UTC, pchelk1n commented on backend/src/User/SignUp/Command/ConfirmEmail.php
> +    public function __invoke(Uuid $confirmToke): void
$confirmToken

2022-12-02 14:21 UTC, pchelk1n commented on backend/src/User/SignUp/Domain/Users.php
> +    public function findByConfirmToken(Uuid $confirmToke): User
$confirmToken

2022-12-19 09:29 UTC, merged