feat(profile): Добавил подмодуль Profile в модуле User
15web/symfony-starter-kit pull request #62
Opened 2023-02-07 20:47 UTC by cazak

META: #89120

2023-02-08 11:02 UTC, pchelk1n commented on backend/src/User/Profile/Domain/ProfilePhone.php
> + * Номер телефона профиля
в профиле

2023-02-08 11:06 UTC, pchelk1n commented on backend/src/User/Profile/Http/ProfileInfoAction.php
> +#[Route('/profiles/{id}', methods: ['GET'])]
А зачем тут ид? ручка просто /profile, берем UserId и по нему находим профиль, если профиля нет, то возвращаем пустую дто

2023-02-08 11:06 UTC, pchelk1n commented on backend/src/User/Profile/Command/SaveProfile/SaveProfile.php
> +        private readonly UpdateProfile $updateProfile,
А зачем нам 2 команды? отличие в том что мы вызываем add  или нет

2023-02-08 11:07 UTC, pchelk1n commented on backend/src/User/Profile/Http/SaveProfile/SaveProfileAction.php
> +#[Route('/profiles/save', methods: ['POST'])]
/profile/save

2023-02-09 09:12 UTC, pchelk1n commented on backend/migrations/Version20230207183929.php
> +        return '';
Добавь описание для чего эта миграция

2023-02-10 13:45 UTC, pchelk1n requested changes

2023-02-10 13:45 UTC, pchelk1n commented on backend/src/User/Profile/Domain/Profiles.php
> +    public function remove(Profile $task): void
Если на будущее, то не надо. YAGNI

2023-02-10 13:45 UTC, pchelk1n commented on backend/tests/Unit/Infrastructure/PhoneTest.php
> +        new Phone('неправильный телефон');
Лучше нормальные разные "неправильные телефоны" проверить через провайдер, граничные случаи.  12 цифр, код больше 9 и т.д.

2023-02-10 14:24 UTC, cazak commented on backend/tests/Unit/Infrastructure/PhoneTest.php
> +        new Phone('неправильный телефон');
Ага, добавил, только код больше 9 не добавил, ведь я по цифрам смотрю, не по числам, а больше 9 цифры нет

2023-02-13 06:37 UTC, pchelk1n approved these changes

2023-02-13 06:37 UTC, merged