feat(php-cs-fixer): Добавил кастомный фиксер на обязательные комментарии
15web/symfony-starter-kit pull request #72
Opened 2023-02-21 20:48 UTC by cazak

META: #90870

2023-02-27 06:48 UTC, pchelk1n requested changes

2023-02-27 06:48 UTC, pchelk1n commented on backend/src-dev/PHPCsFixer/Comment/CommentsForClassFixer.php
> +final class CommentsForClassFixer implements FixerInterface, WhitespacesAwareFixerInterface
ClassDocCommentFixer?

2023-02-27 06:48 UTC, pchelk1n commented on backend/src-dev/PHPCsFixer/Comment/CommentsForClassFixer.php
> +        return sprintf('ClassForComments/%s', 'class_for_comments');
class_doc_comment?

2023-02-27 06:48 UTC, pchelk1n commented on backend/src-dev/PHPCsFixer/Comment/CommentsForClassFixer.php
> +final class Sample
А где тут в примере комментарий?

2023-02-27 06:48 UTC, pchelk1n commented on backend/src-dev/PHPCsFixer/Comment/CommentsForClassFixer.php
> +namespace Dev\PHPCsFixer\Comment;
Dev\PHPCsFixer, пока данного неймспейса нам хватит

2023-02-28 15:23 UTC, cazak commented on backend/src-dev/PHPCsFixer/Comment/CommentsForClassFixer.php
> +final class Sample
Я делал по примеру других фиксеров, там специально указывался неверный пример, я только так и не понял до конца зачем, вроде для тестов

2023-03-01 14:02 UTC, pchelk1n approved these changes

2023-03-01 14:02 UTC, merged