feat(i18n): добавление компонента translator
15web/symfony-starter-kit pull request #89
Opened 2023-03-14 16:37 UTC by vasilevdm

META: #91741

2023-03-16 11:34 UTC, pchelk1n requested changes
Я бы лвинную долю переводов убрал, оставил только те, которые действительно дойдут до клиентов проекта.

2023-03-16 11:34 UTC, pchelk1n commented on backend/src/Article/Http/Admin/UpdateRequest.php
> +        Assert::notEmpty($title, 'article.assert.specify.title');
Уверен, что на ассерты нужны переводы? Это не публичное АПИ, по сути это сообщение для фронта, что он не соблюдает контракт.

2023-03-16 11:34 UTC, pchelk1n commented on backend/src/Article/Http/Admin/CreateAction.php
> +                'article.exception.not_found_by_alias',
А вот это да, это уже фронт покажет клиенту ошибку.

2023-03-16 11:34 UTC, pchelk1n commented on backend/src/Infrastructure/ApiRequestResolver/ApiRequestArgumentValueResolver.php
> +            throw new ApiBadRequestException('infrastructure.exception.invalid_json');
Тут  тоже "системные" сообщения

2023-03-16 11:34 UTC, pchelk1n commented on backend/src/Task/Http/Export/ExportTasks.php
> +            throw new RuntimeException('task.exception.not_found_exporter');
Это сообщение разработчику больше.

2023-03-16 18:07 UTC, vasilevdm commented on backend/src/Article/Http/Admin/UpdateRequest.php
> +        Assert::notEmpty($title, 'article.assert.specify.title');
Если правильно понял логику, то исключения, выбрасываемые ассертами (`InvalidArgumentException`), должны перехватываться и выводится на фронте. Даже если АПИ не публичное, то фронт все равно может работать с разными языками и выводить сообщение ошибки на разных языках.  

Насчет контракта. Для примера данное поле, `title`, помечено в openapi как обязательное. Но при этом пустая строка будет считаться валидным значением. Получается что фронт не нарушает контракт, описанный в openapi, но при этом получает 400 ошибку и может вывести поясняющее сообщение для пользователя "как есть".

Поэтому думаю что если фронт использует сообщения ошибок из ответов апи, то это нужно делать. Если же фронт опирается только на коды, то нет.

2023-03-16 18:28 UTC, vasilevdm commented on backend/src/Task/Http/Export/ExportTasks.php
> +            throw new RuntimeException('task.exception.not_found_exporter');
Согласен, перевод тут не имеет смысла.

2023-03-16 18:43 UTC, vasilevdm commented on backend/src/Infrastructure/ApiRequestResolver/ApiRequestArgumentValueResolver.php
> +            throw new ApiBadRequestException('infrastructure.exception.invalid_json');
Согласен.

2023-03-17 08:06 UTC, pchelk1n commented on backend/src/Article/Http/Admin/UpdateRequest.php
> +        Assert::notEmpty($title, 'article.assert.specify.title');
Фронт не используется данные сообщения, он сам валидирует пользовательский ввод. Данные ассерты это защита от ошибок фронта.

2023-03-27 06:15 UTC, vasilevdm commented on backend/src/Article/Http/Admin/UpdateRequest.php
> +        Assert::notEmpty($title, 'article.assert.specify.title');
Исправил

2023-03-27 06:15 UTC, vasilevdm commented on backend/src/Infrastructure/ApiRequestResolver/ApiRequestArgumentValueResolver.php
> +            throw new ApiBadRequestException('infrastructure.exception.invalid_json');
Исправил

2023-03-27 06:16 UTC, vasilevdm commented on backend/src/Task/Http/Export/ExportTasks.php
> +            throw new RuntimeException('task.exception.not_found_exporter');
Исправил

2023-03-27 06:25 UTC, merged

2023-03-27 06:25 UTC, pchelk1n approved these changes