feat(recoveryPassword): Добавил восстановление пароля
15web/symfony-starter-kit pull request #91
Opened 2023-03-21 10:29 UTC by cazak

META: #89329

2023-03-23 06:52 UTC, pchelk1n requested changes

2023-03-23 06:52 UTC, pchelk1n commented on backend/src/User/RecoveryPassword/Domain/RecoveryTokenNotFoundException.php
> +final class RecoveryTokenNotFoundException extends Exception
Ему точно тут место? В домене не используется данное исключение

2023-03-23 06:52 UTC, pchelk1n commented on backend/src/User/RecoveryPassword/Http/PasswordRecoveryRequestAction.php
> + * Ручка запроса га восстановление пароля
на

2023-03-23 06:52 UTC, pchelk1n commented on backend/src/User/RecoveryPassword/Http/PasswordRecoveryRequestAction.php
> +#[Route('/recover-password-request', methods: ['POST'])]
request password recovery?

2023-03-23 06:52 UTC, pchelk1n commented on backend/src/User/RecoveryPassword/Command/RecoveryPasswordRequestCommand.php
> + * Команда для запроса на восстановление запроса
пароля?

2023-03-23 06:52 UTC, pchelk1n commented on backend/src/User/RecoveryPassword/Command/RecoveryPasswordRequest.php
> +final readonly class RecoveryPasswordRequest
GenerateRecoveryToken?

2023-03-23 06:54 UTC, pchelk1n commented on backend/src/User/RecoveryPassword/Http/PasswordRecoveryAction.php
> +final readonly class PasswordRecoveryAction
RecoverPasswordAction?

2023-03-24 06:37 UTC, pchelk1n requested changes

2023-03-24 06:37 UTC, pchelk1n commented on backend/src/User/RecoveryPassword/Command/GenerateRecoveryToken.php
> +        /** @var ?User $user */
А зачем? В методе же тип описан

2023-03-24 07:39 UTC, cazak commented on backend/src/User/RecoveryPassword/Command/GenerateRecoveryToken.php
> +        /** @var ?User $user */
Не заметил, думал шторм должен такие бесполезные комменты подсвечивать

2023-03-24 08:32 UTC, pchelk1n commented on backend/src/User/RecoveryPassword/Command/GenerateRecoveryToken.php
> +        /** @var ?User $user */
Он подсветит, если ты пхпстан подключить в шторме

2023-03-24 08:32 UTC, pchelk1n approved these changes

2023-03-24 08:33 UTC, merged